trigger:
  batch: true
  branches:
    include:
    - production-*
pr: none

pool:
  name: Hosted macOS
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- script: npm ci
  displayName: 'Install npm dependencies'

- script: npm run build
  workingDirectory: client
  displayName: 'Build the client'
  env:
    NODE_ENV: production
    LOCALE: $(LOCALE)
    NEWS_LOCATION: $(NEWS_LOCATION)
    API_LOCATION: $(API_LOCATION)
    FORUM_LOCATION: $(FORUM_LOCATION)
    ROLLBAR_CLIENT_ID: $(ROLLBAR_CLIENT_ID)
    STRIPE_PUBLIC_KEY: $(STRIPE_PUBLIC_KEY)

- script: |
   npm install netlify-cli -g
   netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir ./public
  workingDirectory: client
  displayName: 'Publish to Netlify'
  env:
    NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
    NETLIFY_ACCESS_TOKEN: $(NETLIFY_ACCESS_TOKEN)
