services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
  api:
    depends_on:
      - mongo
      - mailhog
    image: fcc-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file:
      - .env
    environment:
      # The api cannot connect to mongodb or mailhog via localhost from inside the
      # container, so we have to override these variables.
      - MONGOHQ_URL=mongodb://mongo:27017/freecodecamp?directConnection=true
      - MAILHOG_HOST=mailhog
    ports:
      # PORT is used by the new api, so we use the less generic API_PORT to
      # avoid conflicts.
      - '${API_PORT:-3000}:3000'
  client:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        MONGOHQ_URL: ${MONGOHQ_URL}
        SENTRY_DSN: ${SENTRY_DSN}
        SENTRY_CLIENT_DSN: ${SENTRY_CLIENT_DSN}
        SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
        AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
        AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
        AUTH0_DOMAIN: ${AUTH0_DOMAIN}
        AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
        SESSION_SECRET: ${SESSION_SECRET}
        COOKIE_SECRET: ${COOKIE_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        ALGOLIA_APP_ID: ${ALGOLIA_APP_ID}
        ALGOLIA_API_KEY: ${ALGOLIA_API_KEY}
        STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
        PAYPAL_SECRET: ${PAYPAL_SECRET}
        PAYPAL_VERIFY_WEBHOOK_URL: ${PAYPAL_VERIFY_WEBHOOK_URL}
        PAYPAL_API_TOKEN_URL: ${PAYPAL_API_TOKEN_URL}
        PAYPAL_WEBHOOK_ID: ${PAYPAL_WEBHOOK_ID}
        WEBHOOK_PROXY_URL: ${WEBHOOK_PROXY_URL}
        PATREON_CLIENT_ID: ${PATREON_CLIENT_ID}
        GROWTHBOOK_URI: ${GROWTHBOOK_URI}
        HOME_LOCATION: ${HOME_LOCATION}
        API_LOCATION: ${API_LOCATION}
        FORUM_LOCATION: ${FORUM_LOCATION}
        NEWS_LOCATION: ${NEWS_LOCATION}
        RADIO_LOCATION: ${RADIO_LOCATION}
        DEPLOYMENT_ENV: ${DEPLOYMENT_ENV}
        FREECODECAMP_NODE_ENV: ${FREECODECAMP_NODE_ENV}
        CLIENT_LOCALE: ${CLIENT_LOCALE}
        CURRICULUM_LOCALE: ${CURRICULUM_LOCALE}
        SHOW_UPCOMING_CHANGES: ${SHOW_UPCOMING_CHANGES}
        SHOW_NEW_CURRICULUM: ${SHOW_NEW_CURRICULUM}
        PEER: ${PEER}
        DEBUG: ${DEBUG}
        LOCAL_MOCK_AUTH: ${LOCAL_MOCK_AUTH}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
        FCC_ENABLE_SWAGGER_UI: ${FCC_ENABLE_SWAGGER_UI}
        FCC_ENABLE_DEV_LOGIN_MODE: ${FCC_ENABLE_DEV_LOGIN_MODE}
        EMAIL_PROVIDER: ${EMAIL_PROVIDER}
        SES_ID: ${SES_ID}
        SES_SECRET: ${SES_SECRET}
        SES_REGION: ${SES_REGION}
    image: fcc-client
    env_file:
      - .env
    ports:
      # Same principle as above (avoiding conflicts)
      - '${CLIENT_PORT:-8000}:8000'
