services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  api:
    image: fcc-api
    env_file:
      - .env
    ports:
      - '3000:3000'
  client:
    image: fcc-client
    ports:
      # PORT is used by the new api, so we use the less generic HOST_PORT to avoid
      # conflicts.
      - '${HOST_PORT:-8000}:8000'
