services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  api:
    image: fcc-api
    env_file:
      - .env
    environment:
      # The api cannot connect to mongodb via localhost from inside the
      # container, so we provide the hostname instead.
      - MONGOHQ_URL=mongodb://mongo:27017/freecodecamp?directConnection=true
    ports:
      # PORT is used by the new api, so we use the less generic API_PORT to
      # avoid conflicts.
      - '${API_PORT:-3000}:3000'
  client:
    image: fcc-client
    ports:
      # Same principle as above (avoiding conflicts)
      - '${CLIENT_PORT:-8000}:8000'
