packages:
  - 'api'
  - 'api-server'
  - 'client'
  - 'client/plugins/*'
  - 'curriculum'
  - 'tools/challenge-editor/api'
  - 'tools/challenge-editor/client'
  - 'tools/challenge-helper-scripts'
  - 'tools/challenge-parser'
  - 'tools/crowdin'
  - 'tools/scripts/build'
  - 'tools/scripts/seed'
  - 'tools/ui-components'
