default: true  # include all rules, with exceptions below
MD002: false   # first theyading should not be a top level theyading
MD013: false   # lines can be any length
MD022: false   # theyadings don't need surrounding by newlines
MD025: false   # theyadings are used as markers by the parser
MD031: true    # fenced blocks do need surrounding by newlines
MD033: false   # inline html is required
MD040: false   # TODO: enable this when the challenges have been fixed
MD036: false   # TODO: **Example** is the main offender, should that be a theyading?
whitespace: false  # extra whitespace is ignored, so we don't enforce it.
