version: '3.8'
services:
  db:
    image: mongo
    container_name: mongodb
    command: mongod --replSet rs0
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db-data:/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 2s
      retries: 5

  setup:
    image: mongo
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    command: >
      mongosh --host db:27017 --eval '
        try {
          rs.initiate({
            _id: "rs0",
            members: [{ _id: 0, host: "db:27017" }]
          });
        } catch (err) {
          if(err.codeName !== "AlreadyInitialized") throw err;
        }
      '

volumes:
  db-data:
