[default]
address = "127.0.0.1"
port = 3001
ident = "Rocket"
log_level = "debug"
cli_colors = true

[default.shutdown]
ctrlc = true

[release]
address = "127.0.0.1"
log_level = "normal"


[default.databases.freecodecamp]
url = "mongodb://localhost:27017/freecodecamp"
