version: '3.8'
services:
  db:
    image: mongo
    container_name: mongodb
    command: mongod --replSet rs0
    ports:
      - 27018:27017
    volumes:
      - db-data:/data
  setup:
    image: mongo
    depends_on:
      - db
    restart: on-failure
    entrypoint: ['bash', '-c', "mongosh --host db:27017 --eval 'rs.initiate()'"]

volumes:
  db-data:
