name: Run development server on all OS
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-dev-server:
    name: Run development server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    services:
      mongodb:
        image: mongo:3.6.19
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [12.x]
        os:
          [
            ubuntu-16.04,
            ubuntu-18.04,
            ubuntu-20.04,
            windows-latest,
            macos-latest,
          ]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Install Dependencies
        run: |
          npm ci
          npm run ensure-env

      - name: Seed Database
        run: npm run seed

      - name: Run Dev Server
        run: npm run development
