name: "No changing translated files on GitHub"
on:
  pull_request:
    branches:
    - 'master'
    paths:
    - 'curriculum/challenges/**'
    - '!curriculum/challenges/english/**'

jobs:
  has-translation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v3
      if: github.event.pull_request.user.login != "github-actions[bot]"
      with:
        script: |
          throw "You appear to be translating files directly on GitHub. Please use Crowdin instead."
