name: Node.js CI
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Lint Source Files
        run: |
          npm ci
          npm run ensure-env --if-present
          npm run lint --if-present

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Install Dependencies
        run: |
          npm ci
          npm run ensure-env --if-present

      - name: Run Tests
        run: npm test

  ensure-dev-server:
    name: Run Dev Server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-16.04, macos-latest]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.6

      - name: Seed MongoDB
        run: npm run seed

      - name: Run Dev Server
        run: npm run develop

  ensure-production-server:
    name: Build Production Server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-16.04, macos-latest]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 3.6

      - name: Seed MongoDB
        run: npm run seed

      - name: Build Production Server
        run: npm run build

      - name: Start Production Server
        run: npm run start

  ensure-dev-server-on-windows:
    name: Run Dev Server on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Environment variables
        run: cp sample.env .env

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB
        run: |
          powershell
          $wc.DownloadFile("https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-3.6.19-signed.msi", "mongodb-win32-x86_64-2008plus-ssl-3.6.19-signed.msi")
          ls
          msiexec.exe /q /i mongodb-win32-x86_64-2008plus-ssl-3.6.19-signed.msi

      - name: Seed MongoDB
        run: npm run seed

      - name: Run Dev Server
        run: npm run develop
