name: Synch Changes to New Repo

# Deploy pipeline rules when a PR containing changes related to
# pipeline rules is merged to the 'main' branch

"on":
  push:
    # branches:
      # - main
    # paths:
      - #TODO

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  synch-changes:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            shared
            curriculum
          fetch-depth: 3
      - name: Run Git synch
        run: |
          cd ../
          git clone https://github.com/Asad-Rahim/FreeCodeCampCopy.git
          echo "${PWD}"
          echo "$(${PWD}/freeCodeCamp/git_synch.sh"